#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AEP_s503X_LV1_sp

#include "Basic.hpp"

#include "AEP_Player_Attacks_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AEP_s503X_LV1_sp.AEP_s503X_LV1_sp_C
// 0x0000 (0x0370 - 0x0370)
class UAEP_s503X_LV1_sp_C : public UAEP_Player_Attacks_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AEP_s503X_LV1_sp_C">();
	}
	static class UAEP_s503X_LV1_sp_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAEP_s503X_LV1_sp_C>();
	}
};
static_assert(alignof(UAEP_s503X_LV1_sp_C) == 0x000010, "Wrong alignment on UAEP_s503X_LV1_sp_C");
static_assert(sizeof(UAEP_s503X_LV1_sp_C) == 0x000370, "Wrong size on UAEP_s503X_LV1_sp_C");

}

