#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ActorSpawner_Generic_Shop

#include "Basic.hpp"

#include "BP_ActorSpawner_Generic_Shop_classes.hpp"
#include "BP_ActorSpawner_Generic_Shop_parameters.hpp"


namespace SDK
{

// Function BP_ActorSpawner_Generic_Shop.BP_ActorSpawner_Generic_Shop_C.OnPostSpawnActor
// (Event, Protected, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    bPreview                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ActorSpawner_Generic_Shop_C::OnPostSpawnActor(class AActor* Actor, bool bPreview)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActorSpawner_Generic_Shop_C", "OnPostSpawnActor");

	Params::BP_ActorSpawner_Generic_Shop_C_OnPostSpawnActor Parms{};

	Parms.Actor = Actor;
	Parms.bPreview = bPreview;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ActorSpawner_Generic_Shop.BP_ActorSpawner_Generic_Shop_C.GetMapIconGameplayConditions
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FGameplayConditionChecker*       OutConditionChecker                                    (Parm, OutParm, ContainsInstancedReference)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABP_ActorSpawner_Generic_Shop_C::GetMapIconGameplayConditions(struct FGameplayConditionChecker* OutConditionChecker)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActorSpawner_Generic_Shop_C", "GetMapIconGameplayConditions");

	Params::BP_ActorSpawner_Generic_Shop_C_GetMapIconGameplayConditions Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutConditionChecker != nullptr)
		*OutConditionChecker = std::move(Parms.OutConditionChecker);

	return Parms.ReturnValue;
}


// Function BP_ActorSpawner_Generic_Shop.BP_ActorSpawner_Generic_Shop_C.GetMapIconActorWithDependencies
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMapIconProviderData*            OutMapIconProviderData                                 (Parm, OutParm)

void ABP_ActorSpawner_Generic_Shop_C::GetMapIconActorWithDependencies(struct FMapIconProviderData* OutMapIconProviderData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActorSpawner_Generic_Shop_C", "GetMapIconActorWithDependencies");

	Params::BP_ActorSpawner_Generic_Shop_C_GetMapIconActorWithDependencies Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (OutMapIconProviderData != nullptr)
		*OutMapIconProviderData = std::move(Parms.OutMapIconProviderData);
}


// Function BP_ActorSpawner_Generic_Shop.BP_ActorSpawner_Generic_Shop_C.ExecuteUbergraph_BP_ActorSpawner_Generic_Shop
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ActorSpawner_Generic_Shop_C::ExecuteUbergraph_BP_ActorSpawner_Generic_Shop(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ActorSpawner_Generic_Shop_C", "ExecuteUbergraph_BP_ActorSpawner_Generic_Shop");

	Params::BP_ActorSpawner_Generic_Shop_C_ExecuteUbergraph_BP_ActorSpawner_Generic_Shop Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

