#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CharacterZion_Boss

#include "Basic.hpp"

#include "BP_CharacterZion_Enemy_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CharacterZion_Boss.BP_CharacterZion_Boss_C
// 0x0000 (0x0A20 - 0x0A20)
#pragma pack(push, 0x1)
class alignas(0x10) ABP_CharacterZion_Boss_C : public ABP_CharacterZion_Enemy_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_CharacterZion_Boss_C">();
	}
	static class ABP_CharacterZion_Boss_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CharacterZion_Boss_C>();
	}
};
#pragma pack(pop)
static_assert(alignof(ABP_CharacterZion_Boss_C) == 0x000010, "Wrong alignment on ABP_CharacterZion_Boss_C");
static_assert(sizeof(ABP_CharacterZion_Boss_C) == 0x000A20, "Wrong size on ABP_CharacterZion_Boss_C");

}

