#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_n0302_Server

#include "Basic.hpp"

#include "BP_CharacterZionNPC_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_n0302_Server.BP_n0302_Server_C
// 0x0000 (0x0790 - 0x0790)
class ABP_n0302_Server_C  : public ABP_CharacterZionNPC_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_n0302_Server_C">();
	}
	static class ABP_n0302_Server_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_n0302_Server_C>();
	}
};
static_assert(alignof(ABP_n0302_Server_C) == 0x000010, "Wrong alignment on ABP_n0302_Server_C");
static_assert(sizeof(ABP_n0302_Server_C) == 0x000790, "Wrong size on ABP_n0302_Server_C");

}

