#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlayerControllerZion

#include "Basic.hpp"

#include "BP_PlayerControllerZion_classes.hpp"
#include "BP_PlayerControllerZion_parameters.hpp"


namespace SDK
{

// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.AddCommand
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UClass*                           Command                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::AddCommand(class UClass* Command)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "AddCommand");

	Params::BP_PlayerControllerZion_C_AddCommand Parms{};

	Parms.Command = Command;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.AddFastTravelCommand
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::AddFastTravelCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "AddFastTravelCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.AddWakeUpCommand
// (Private, BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::AddWakeUpCommand()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "AddWakeUpCommand");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.BndEvt__BP_PlayerControllerZion_HealComponent_K2Node_ComponentBoundEvent_1_RestoreHealsEvent__DelegateSignature
// (BlueprintEvent)
// Parameters:
// int32                                   RestoredHealCount                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::BndEvt__BP_PlayerControllerZion_HealComponent_K2Node_ComponentBoundEvent_1_RestoreHealsEvent__DelegateSignature(int32 RestoredHealCount)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "BndEvt__BP_PlayerControllerZion_HealComponent_K2Node_ComponentBoundEvent_1_RestoreHealsEvent__DelegateSignature");

	Params::BP_PlayerControllerZion_C_BndEvt__BP_PlayerControllerZion_HealComponent_K2Node_ComponentBoundEvent_1_RestoreHealsEvent__DelegateSignature Parms{};

	Parms.RestoredHealCount = RestoredHealCount;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.BndEvt__BP_PlayerControllerZion_StatsControllerPlayerComponent_K2Node_ComponentBoundEvent_0_StatsPlayerDelegate__DelegateSignature
// (BlueprintEvent)

void ABP_PlayerControllerZion_C::BndEvt__BP_PlayerControllerZion_StatsControllerPlayerComponent_K2Node_ComponentBoundEvent_0_StatsPlayerDelegate__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "BndEvt__BP_PlayerControllerZion_StatsControllerPlayerComponent_K2Node_ComponentBoundEvent_0_StatsPlayerDelegate__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.CanOpenMenu
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bResult                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::CanOpenMenu(bool* bResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "CanOpenMenu");

	Params::BP_PlayerControllerZion_C_CanOpenMenu Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bResult != nullptr)
		*bResult = Parms.bResult;
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.CloseAllMenus
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::CloseAllMenus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "CloseAllMenus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.ExecuteUbergraph_BP_PlayerControllerZion
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::ExecuteUbergraph_BP_PlayerControllerZion(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "ExecuteUbergraph_BP_PlayerControllerZion");

	Params::BP_PlayerControllerZion_C_ExecuteUbergraph_BP_PlayerControllerZion Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.FindInteractableRestPoint
// (Private, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class ABP_Interactable_RestPoint_C**    Array_Element                                          (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::FindInteractableRestPoint(class ABP_Interactable_RestPoint_C** Array_Element)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "FindInteractableRestPoint");

	Params::BP_PlayerControllerZion_C_FindInteractableRestPoint Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Array_Element != nullptr)
		*Array_Element = Parms.Array_Element;
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.InpActEvt_IA_Debug_Menu_K2Node_EnhancedInputActionEvent_1
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::InpActEvt_IA_Debug_Menu_K2Node_EnhancedInputActionEvent_1(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "InpActEvt_IA_Debug_Menu_K2Node_EnhancedInputActionEvent_1");

	Params::BP_PlayerControllerZion_C_InpActEvt_IA_Debug_Menu_K2Node_EnhancedInputActionEvent_1 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.InpActEvt_IA_Menu_K2Node_EnhancedInputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::InpActEvt_IA_Menu_K2Node_EnhancedInputActionEvent_0(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "InpActEvt_IA_Menu_K2Node_EnhancedInputActionEvent_0");

	Params::BP_PlayerControllerZion_C_InpActEvt_IA_Menu_K2Node_EnhancedInputActionEvent_0 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.InpActEvt_IA_Pause_K2Node_EnhancedInputActionEvent_2
// (BlueprintEvent)
// Parameters:
// const struct FInputActionValue&         ActionValue                                            (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// float                                   ElapsedTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   TriggeredTime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class UInputAction*               SourceAction                                           (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::InpActEvt_IA_Pause_K2Node_EnhancedInputActionEvent_2(const struct FInputActionValue& ActionValue, float ElapsedTime, float TriggeredTime, const class UInputAction* SourceAction)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "InpActEvt_IA_Pause_K2Node_EnhancedInputActionEvent_2");

	Params::BP_PlayerControllerZion_C_InpActEvt_IA_Pause_K2Node_EnhancedInputActionEvent_2 Parms{};

	Parms.ActionValue = std::move(ActionValue);
	Parms.ElapsedTime = ElapsedTime;
	Parms.TriggeredTime = TriggeredTime;
	Parms.SourceAction = SourceAction;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.LaunchTutorial
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             TutorialID                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::LaunchTutorial(class FName TutorialID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "LaunchTutorial");

	Params::BP_PlayerControllerZion_C_LaunchTutorial Parms{};

	Parms.TutorialID = TutorialID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnAchievementUnlocked
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      AchievementID                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::OnAchievementUnlocked(const class FName& AchievementID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnAchievementUnlocked");

	Params::BP_PlayerControllerZion_C_OnAchievementUnlocked Parms{};

	Parms.AchievementID = AchievementID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnCloseDebugMenu
// (BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnCloseDebugMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnCloseDebugMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnClosedGameMenu
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   PageIndex                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::OnClosedGameMenu(int32 PageIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnClosedGameMenu");

	Params::BP_PlayerControllerZion_C_OnClosedGameMenu Parms{};

	Parms.PageIndex = PageIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnClosedPauseMenu
// (BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnClosedPauseMenu()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnClosedPauseMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnDisplayAreaName
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      AreaName                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::OnDisplayAreaName(const class FName& AreaName)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnDisplayAreaName");

	Params::BP_PlayerControllerZion_C_OnDisplayAreaName Parms{};

	Parms.AreaName = AreaName;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnDisplayAreaNameWidgetDestroyed
// (BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnDisplayAreaNameWidgetDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnDisplayAreaNameWidgetDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnFinish_532910D747F253B9D57DB093F3A34C09
// (BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnFinish_532910D747F253B9D57DB093F3A34C09()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnFinish_532910D747F253B9D57DB093F3A34C09");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnGameMapChangeFinished
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const class FName&                      GameMapID                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::OnGameMapChangeFinished(const class FName& GameMapID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnGameMapChangeFinished");

	Params::BP_PlayerControllerZion_C_OnGameMapChangeFinished Parms{};

	Parms.GameMapID = GameMapID;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnGameMapChangeStart
// (Event, Protected, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnGameMapChangeStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnGameMapChangeStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnRequestTutorials
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const TArray<class FName>&              TutorialIDs                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ABP_PlayerControllerZion_C::OnRequestTutorials(const TArray<class FName>& TutorialIDs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnRequestTutorials");

	Params::BP_PlayerControllerZion_C_OnRequestTutorials Parms{};

	Parms.TutorialIDs = std::move(TutorialIDs);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnRespawnCompleted
// (Event, Protected, BlueprintEvent)
// Parameters:
// ERespawnReason                          RespawnReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_PlayerControllerZion_C::OnRespawnCompleted(ERespawnReason RespawnReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnRespawnCompleted");

	Params::BP_PlayerControllerZion_C_OnRespawnCompleted Parms{};

	Parms.RespawnReason = RespawnReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnStoryLevelChanged
// (Event, Protected, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnStoryLevelChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnStoryLevelChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_PlayerControllerZion.BP_PlayerControllerZion_C.OnTutorialClosed
// (BlueprintCallable, BlueprintEvent)

void ABP_PlayerControllerZion_C::OnTutorialClosed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_PlayerControllerZion_C", "OnTutorialClosed");

	UObject::ProcessEvent(Func, nullptr);
}

}

