#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CMD_e0220_DashTo_Cancel

#include "Basic.hpp"

#include "BP_Command_AI_DashTo_Cancel_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CMD_e0220_DashTo_Cancel.CMD_e0220_DashTo_Cancel_C
// 0x0000 (0x0490 - 0x0490)
class UCMD_e0220_DashTo_Cancel_C  : public UBP_Command_AI_DashTo_Cancel_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CMD_e0220_DashTo_Cancel_C">();
	}
	static class UCMD_e0220_DashTo_Cancel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCMD_e0220_DashTo_Cancel_C>();
	}
};
static_assert(alignof(UCMD_e0220_DashTo_Cancel_C) == 0x000010, "Wrong alignment on UCMD_e0220_DashTo_Cancel_C");
static_assert(sizeof(UCMD_e0220_DashTo_Cancel_C) == 0x000490, "Wrong size on UCMD_e0220_DashTo_Cancel_C");

}

