#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DM_GuardBack

#include "Basic.hpp"

#include "DM_Base_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DM_GuardBack.DM_GuardBack_C
// 0x0000 (0x0360 - 0x0360)
class UDM_GuardBack_C final : public UDM_Base_C
{
public:
	void ToggleModule();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DM_GuardBack_C">();
	}
	static class UDM_GuardBack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDM_GuardBack_C>();
	}
};
static_assert(alignof(UDM_GuardBack_C) == 0x000008, "Wrong alignment on UDM_GuardBack_C");
static_assert(sizeof(UDM_GuardBack_C) == 0x000360, "Wrong size on UDM_GuardBack_C");

}

