#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RenderLayer

#include "Basic.hpp"

#include "RenderLayer_structs.hpp"


namespace SDK::Params
{

// Function RenderLayer.RenderLayerSubsystem.GetPriorityForRenderLayer
// 0x0008 (0x0008 - 0x0000)
struct RenderLayerSubsystem_GetPriorityForRenderLayer final
{
public:
	ERenderLayerTypes                             RenderLayer;                                       // 0x0000(0x0001)(ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         ReturnValue;                                       // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(RenderLayerSubsystem_GetPriorityForRenderLayer) == 0x000004, "Wrong alignment on RenderLayerSubsystem_GetPriorityForRenderLayer");
static_assert(sizeof(RenderLayerSubsystem_GetPriorityForRenderLayer) == 0x000008, "Wrong size on RenderLayerSubsystem_GetPriorityForRenderLayer");
static_assert(offsetof(RenderLayerSubsystem_GetPriorityForRenderLayer, RenderLayer) == 0x000000, "Member 'RenderLayerSubsystem_GetPriorityForRenderLayer::RenderLayer' has a wrong offset!");
static_assert(offsetof(RenderLayerSubsystem_GetPriorityForRenderLayer, ReturnValue) == 0x000004, "Member 'RenderLayerSubsystem_GetPriorityForRenderLayer::ReturnValue' has a wrong offset!");

}

