#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Title

#include "Basic.hpp"

#include "Title_classes.hpp"
#include "Title_parameters.hpp"


namespace SDK
{

// Function Title.Title_C.CanUseGammaSetting
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   bCanUseGamma                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATitle_C::CanUseGammaSetting(bool* bCanUseGamma)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CanUseGammaSetting");

	Params::Title_C_CanUseGammaSetting Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (bCanUseGamma != nullptr)
		*bCanUseGamma = Parms.bCanUseGamma;
}


// Function Title.Title_C.CreateAutoUploadCrashSetting
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::CreateAutoUploadCrashSetting()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CreateAutoUploadCrashSetting");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.CreateGammaSelection
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::CreateGammaSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CreateGammaSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.CreateLanguageSelection
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::CreateLanguageSelection()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CreateLanguageSelection");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.CreateProfileConfirmationUI
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::CreateProfileConfirmationUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CreateProfileConfirmationUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.CreateTitleUI
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::CreateTitleUI()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "CreateTitleUI");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.DoInitialSettingsProcess
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::DoInitialSettingsProcess()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "DoInitialSettingsProcess");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.ExecuteUbergraph_Title
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATitle_C::ExecuteUbergraph_Title(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "ExecuteUbergraph_Title");

	Params::Title_C_ExecuteUbergraph_Title Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Title.Title_C.FinalizeInitialSettings
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::FinalizeInitialSettings()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "FinalizeInitialSettings");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.LoadSettingsData
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void ATitle_C::LoadSettingsData()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "LoadSettingsData");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnAutoUploadCrashNO
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnAutoUploadCrashNO()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnAutoUploadCrashNO");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnAutoUploadCrashYES
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnAutoUploadCrashYES()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnAutoUploadCrashYES");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnCancelSettingsDeletion
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnCancelSettingsDeletion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnCancelSettingsDeletion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnGammaSelected
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bConfirmed                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATitle_C::OnGammaSelected(bool bConfirmed)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnGammaSelected");

	Params::Title_C_OnGammaSelected Parms{};

	Parms.bConfirmed = bConfirmed;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Title.Title_C.OnLanguageSelecitonFinished
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnLanguageSelecitonFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnLanguageSelecitonFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnProfileConfirmationFinished
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnProfileConfirmationFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnProfileConfirmationFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnRequestSettingsDeletion
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnRequestSettingsDeletion()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnRequestSettingsDeletion");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.OnSettingsLoaded
// (BlueprintCallable, BlueprintEvent)

void ATitle_C::OnSettingsLoaded()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "OnSettingsLoaded");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ATitle_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Title.Title_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ATitle_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "ReceiveEndPlay");

	Params::Title_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Title.Title_C.SetupProfile
// (Private, BlueprintCallable, BlueprintEvent)

void ATitle_C::SetupProfile()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Title_C", "SetupProfile");

	UObject::ProcessEvent(Func, nullptr);
}

}

