#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BossHPGauge

#include "Basic.hpp"

#include "WBP_BossHPGauge_classes.hpp"
#include "WBP_BossHPGauge_parameters.hpp"


namespace SDK
{

// Function WBP_BossHPGauge.WBP_BossHPGauge_C.SetDelayedGaugeVisible
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BossHPGauge_C::SetDelayedGaugeVisible(bool Visible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "SetDelayedGaugeVisible");

	Params::WBP_BossHPGauge_C_SetDelayedGaugeVisible Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshSettingsVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::RefreshSettingsVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshSettingsVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshName
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FEnemyData&                EnemyData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_BossHPGauge_C::RefreshName(const struct FEnemyData& EnemyData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshName");

	Params::WBP_BossHPGauge_C_RefreshName Parms{};

	Parms.EnemyData = std::move(EnemyData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshHPTextVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::RefreshHPTextVisibility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshHPTextVisibility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshHPText
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::RefreshHPText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshHPText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshHPGauge
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    RefreshDelayedGauge                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BossHPGauge_C::RefreshHPGauge(bool RefreshDelayedGauge)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshHPGauge");

	Params::WBP_BossHPGauge_C_RefreshHPGauge Parms{};

	Parms.RefreshDelayedGauge = RefreshDelayedGauge;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.RefreshDelayedHP
// (BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::RefreshDelayedHP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "RefreshDelayedHP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.OnReceiveDamage
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Source                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32                                   Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BossHPGauge_C::OnReceiveDamage(class AActor* Source, int32 Value)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "OnReceiveDamage");

	Params::WBP_BossHPGauge_C_OnReceiveDamage Parms{};

	Parms.Source = Source;
	Parms.Value = Value;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.OnHPChanged
// (BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::OnHPChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "OnHPChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.OnDisplaySettingsChanged
// (BlueprintCallable, BlueprintEvent)

void UWBP_BossHPGauge_C::OnDisplaySettingsChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "OnDisplaySettingsChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            Pawn                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FEnemyData&                EnemyData                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_BossHPGauge_C::Initialize(class APawn* Pawn, const struct FEnemyData& EnemyData)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "Initialize");

	Params::WBP_BossHPGauge_C_Initialize Parms{};

	Parms.Pawn = Pawn;
	Parms.EnemyData = std::move(EnemyData);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.GetHPRatio
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double*                                 HPRatio                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BossHPGauge_C::GetHPRatio(double* HPRatio)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "GetHPRatio");

	Params::WBP_BossHPGauge_C_GetHPRatio Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (HPRatio != nullptr)
		*HPRatio = Parms.HPRatio;
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.ExecuteUbergraph_WBP_BossHPGauge
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_BossHPGauge_C::ExecuteUbergraph_WBP_BossHPGauge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "ExecuteUbergraph_WBP_BossHPGauge");

	Params::WBP_BossHPGauge_C_ExecuteUbergraph_WBP_BossHPGauge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_BossHPGauge_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_BossHPGauge.WBP_BossHPGauge_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_BossHPGauge_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_BossHPGauge_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}

}

