#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_HealingItemIcon

#include "Basic.hpp"

#include "WBP_HealingItemIcon_classes.hpp"
#include "WBP_HealingItemIcon_parameters.hpp"


namespace SDK
{

// Function WBP_HealingItemIcon.WBP_HealingItemIcon_C.RestoreItem
// (BlueprintCallable, BlueprintEvent)

void UWBP_HealingItemIcon_C::RestoreItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealingItemIcon_C", "RestoreItem");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_HealingItemIcon.WBP_HealingItemIcon_C.MarkUsed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    SkipAnimation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealingItemIcon_C::MarkUsed(bool SkipAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealingItemIcon_C", "MarkUsed");

	Params::WBP_HealingItemIcon_C_MarkUsed Parms{};

	Parms.SkipAnimation = SkipAnimation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_HealingItemIcon.WBP_HealingItemIcon_C.ExecuteUbergraph_WBP_HealingItemIcon
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_HealingItemIcon_C::ExecuteUbergraph_WBP_HealingItemIcon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_HealingItemIcon_C", "ExecuteUbergraph_WBP_HealingItemIcon");

	Params::WBP_HealingItemIcon_C_ExecuteUbergraph_WBP_HealingItemIcon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

