#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Recollection_Page_Bosses

#include "Basic.hpp"

#include "WBP_Recollection_Page_Bosses_classes.hpp"
#include "WBP_Recollection_Page_Bosses_parameters.hpp"


namespace SDK
{

// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.BndEvt__WBP_Recollection_Page_Bosses_WBP_Recollection_Boss_NGSelection_K2Node_ComponentBoundEvent_0_OnFocused__DelegateSignature
// (BlueprintEvent)

void UWBP_Recollection_Page_Bosses_C::BndEvt__WBP_Recollection_Page_Bosses_WBP_Recollection_Boss_NGSelection_K2Node_ComponentBoundEvent_0_OnFocused__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "BndEvt__WBP_Recollection_Page_Bosses_WBP_Recollection_Boss_NGSelection_K2Node_ComponentBoundEvent_0_OnFocused__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Recollection_Page_Bosses_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.DoCustomNavigation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, NoDestructor, HasGetValueTypeHash)

class UWidget* UWBP_Recollection_Page_Bosses_C::DoCustomNavigation(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "DoCustomNavigation");

	Params::WBP_Recollection_Page_Bosses_C_DoCustomNavigation Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.ExecuteUbergraph_WBP_Recollection_Page_Bosses
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Recollection_Page_Bosses_C::ExecuteUbergraph_WBP_Recollection_Page_Bosses(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "ExecuteUbergraph_WBP_Recollection_Page_Bosses");

	Params::WBP_Recollection_Page_Bosses_C_ExecuteUbergraph_WBP_Recollection_Page_Bosses Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.FocusBossEntry
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDataTableRowHandle&       RecollectionBossHandle                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UWBP_Recollection_Page_Bosses_C::FocusBossEntry(const struct FDataTableRowHandle& RecollectionBossHandle)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "FocusBossEntry");

	Params::WBP_Recollection_Page_Bosses_C_FocusBossEntry Parms{};

	Parms.RecollectionBossHandle = std::move(RecollectionBossHandle);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.GenerateEntries
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Recollection_Page_Bosses_C::GenerateEntries()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "GenerateEntries");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.OnAddedToFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_Recollection_Page_Bosses_C::OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "OnAddedToFocusPath");

	Params::WBP_Recollection_Page_Bosses_C_OnAddedToFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.OnButtonPressed
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_Recollection_Button_C*       Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FKeyEvent&                 KeyEvent                                               (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Recollection_Page_Bosses_C::OnButtonPressed(class UWBP_Recollection_Button_C* Button, const struct FKeyEvent& KeyEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "OnButtonPressed");

	Params::WBP_Recollection_Page_Bosses_C_OnButtonPressed Parms{};

	Parms.Button = Button;
	Parms.KeyEvent = std::move(KeyEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_Recollection_Page_Bosses_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "OnFocusReceived");

	Params::WBP_Recollection_Page_Bosses_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.OnRemovedFromFocusPath
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)

void UWBP_Recollection_Page_Bosses_C::OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "OnRemovedFromFocusPath");

	Params::WBP_Recollection_Page_Bosses_C_OnRemovedFromFocusPath Parms{};

	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Recollection_Page_Bosses_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "PreConstruct");

	Params::WBP_Recollection_Page_Bosses_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.RequestStartRecollectionBoss
// (BlueprintCallable, BlueprintEvent)

void UWBP_Recollection_Page_Bosses_C::RequestStartRecollectionBoss()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "RequestStartRecollectionBoss");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Recollection_Page_Bosses.WBP_Recollection_Page_Bosses_C.SetupNavigation
// (Private, BlueprintCallable, BlueprintEvent)

void UWBP_Recollection_Page_Bosses_C::SetupNavigation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Recollection_Page_Bosses_C", "SetupNavigation");

	UObject::ProcessEvent(Func, nullptr);
}

}

