#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapIcon_Interactable_MagicDoor

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Zion_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_MapIcon_Interactable_MagicDoor.WBP_MapIcon_Interactable_MagicDoor_C
// 0x0010 (0x05F8 - 0x05E8)
class UWBP_MapIcon_Interactable_MagicDoor_C final : public UUserWidgetMapIcon_Clearable
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x05E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBorder*                                StickyBorder;                                      // 0x05F0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ClearIcon();
	void ExecuteUbergraph_WBP_MapIcon_Interactable_MagicDoor(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_MapIcon_Interactable_MagicDoor_C">();
	}
	static class UWBP_MapIcon_Interactable_MagicDoor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MapIcon_Interactable_MagicDoor_C>();
	}
};
static_assert(alignof(UWBP_MapIcon_Interactable_MagicDoor_C) == 0x000008, "Wrong alignment on UWBP_MapIcon_Interactable_MagicDoor_C");
static_assert(sizeof(UWBP_MapIcon_Interactable_MagicDoor_C) == 0x0005F8, "Wrong size on UWBP_MapIcon_Interactable_MagicDoor_C");
static_assert(offsetof(UWBP_MapIcon_Interactable_MagicDoor_C, UberGraphFrame) == 0x0005E8, "Member 'UWBP_MapIcon_Interactable_MagicDoor_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_MapIcon_Interactable_MagicDoor_C, StickyBorder) == 0x0005F0, "Member 'UWBP_MapIcon_Interactable_MagicDoor_C::StickyBorder' has a wrong offset!");

}

