#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Item_PassiveData

#include "Basic.hpp"

#include "Zion_structs.hpp"


namespace SDK::Params
{

// Function WBP_Item_PassiveData.WBP_Item_PassiveData_C.Setup
// 0x0278 (0x0278 - 0x0000)
struct WBP_Item_PassiveData_C_Setup final
{
public:
	struct FInventoryItemPassiveData              PassiveData;                                       // 0x0000(0x0268)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0268(0x0010)()
};
static_assert(alignof(WBP_Item_PassiveData_C_Setup) == 0x000008, "Wrong alignment on WBP_Item_PassiveData_C_Setup");
static_assert(sizeof(WBP_Item_PassiveData_C_Setup) == 0x000278, "Wrong size on WBP_Item_PassiveData_C_Setup");
static_assert(offsetof(WBP_Item_PassiveData_C_Setup, PassiveData) == 0x000000, "Member 'WBP_Item_PassiveData_C_Setup::PassiveData' has a wrong offset!");
static_assert(offsetof(WBP_Item_PassiveData_C_Setup, CallFunc_Conv_IntToText_ReturnValue) == 0x000268, "Member 'WBP_Item_PassiveData_C_Setup::CallFunc_Conv_IntToText_ReturnValue' has a wrong offset!");

}

