#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Settings

#include "Basic.hpp"

#include "UMG_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function WBP_Settings.WBP_Settings_C.ExecuteUbergraph_WBP_Settings
// 0x0148 (0x0148 - 0x0000)
struct WBP_Settings_C_ExecuteUbergraph_WBP_Settings final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USaveSubsystem*                         CallFunc_GetGameInstanceSubsystem_ReturnValue;     // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UUMGSubsystem*                          CallFunc_GetGameInstanceSubsystem_ReturnValue_1;   // 0x0020(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_SaveSettings_ReturnValue;                 // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSubsystem*                          CallFunc_GetGameInstanceSubsystem_ReturnValue_2;   // 0x0030(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsSwitchBuild_ReturnValue;                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPlaystationBuild_ReturnValue;           // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_3A[0x6];                                       // 0x003A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_SelectText_ReturnValue;                   // 0x0040(0x0010)()
	class FText                                   CallFunc_SelectText_ReturnValue_1;                 // 0x0050(0x0010)()
	class UPlayUMGAnimationAsyncAction*           CallFunc_PlayUMGAnimation_ReturnValue;             // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0068(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_69[0x3];                                       // 0x0069(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_1;            // 0x006C(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameUserSettings*                      CallFunc_GetGameUserSettings_ReturnValue;          // 0x0080(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class UPlayUMGAnimationAsyncAction*           CallFunc_PlayUMGAnimation_ReturnValue_1;           // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FKeyEvent                              K2Node_CustomEvent_KeyEvent_1;                     // 0x0098(0x0040)()
	class UWBP_Button_Tab_C*                      K2Node_CustomEvent_PressedButtonTab_1;             // 0x00D8(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_InFocusEvent;                         // 0x00E0(0x0008)(NoDestructor)
	struct FKeyEvent                              K2Node_CustomEvent_KeyEvent;                       // 0x00E8(0x0040)()
	class UWBP_GameMenu_Tab_C*                    K2Node_CustomEvent_PressedButtonTab;               // 0x0128(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UNativeWidgetHost*                      K2Node_Event_FocusedWidgetHost;                    // 0x0130(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            K2Node_Event_FocusEvent;                           // 0x0138(0x0008)(ConstParm, NoDestructor)
	int32                                         CallFunc_Array_Find_ReturnValue;                   // 0x0140(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_IsDesignTime;                         // 0x0144(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings) == 0x000008, "Wrong alignment on WBP_Settings_C_ExecuteUbergraph_WBP_Settings");
static_assert(sizeof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings) == 0x000148, "Wrong size on WBP_Settings_C_ExecuteUbergraph_WBP_Settings");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, EntryPoint) == 0x000000, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::EntryPoint' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_GetGameInstanceSubsystem_ReturnValue) == 0x000018, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_GetGameInstanceSubsystem_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_GetGameInstanceSubsystem_ReturnValue_1) == 0x000020, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_GetGameInstanceSubsystem_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_SaveSettings_ReturnValue) == 0x000028, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_SaveSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_GetGameInstanceSubsystem_ReturnValue_2) == 0x000030, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_GetGameInstanceSubsystem_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_IsSwitchBuild_ReturnValue) == 0x000038, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_IsSwitchBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_IsPlaystationBuild_ReturnValue) == 0x000039, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_IsPlaystationBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_SelectText_ReturnValue) == 0x000040, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_SelectText_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_SelectText_ReturnValue_1) == 0x000050, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_SelectText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_PlayUMGAnimation_ReturnValue) == 0x000060, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_PlayUMGAnimation_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_IsValid_ReturnValue) == 0x000068, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CreateDelegate_OutputDelegate_1) == 0x00006C, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_GetGameUserSettings_ReturnValue) == 0x000080, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_GetGameUserSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_PlayUMGAnimation_ReturnValue_1) == 0x000088, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_PlayUMGAnimation_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_IsValid_ReturnValue_1) == 0x000090, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CustomEvent_KeyEvent_1) == 0x000098, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CustomEvent_KeyEvent_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CustomEvent_PressedButtonTab_1) == 0x0000D8, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CustomEvent_PressedButtonTab_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_Event_InFocusEvent) == 0x0000E0, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_Event_InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CustomEvent_KeyEvent) == 0x0000E8, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CustomEvent_KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_CustomEvent_PressedButtonTab) == 0x000128, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_CustomEvent_PressedButtonTab' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_Event_FocusedWidgetHost) == 0x000130, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_Event_FocusedWidgetHost' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_Event_FocusEvent) == 0x000138, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_Event_FocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, CallFunc_Array_Find_ReturnValue) == 0x000140, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::CallFunc_Array_Find_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_ExecuteUbergraph_WBP_Settings, K2Node_Event_IsDesignTime) == 0x000144, "Member 'WBP_Settings_C_ExecuteUbergraph_WBP_Settings::K2Node_Event_IsDesignTime' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.GetNewPageIndex
// 0x001C (0x001C - 0x0000)
struct WBP_Settings_C_GetNewPageIndex final
{
public:
	int32                                         PageOffset;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         NewPageIndex;                                      // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_LoopAround_ReturnValue;                   // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_GetNewPageIndex) == 0x000004, "Wrong alignment on WBP_Settings_C_GetNewPageIndex");
static_assert(sizeof(WBP_Settings_C_GetNewPageIndex) == 0x00001C, "Wrong size on WBP_Settings_C_GetNewPageIndex");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, PageOffset) == 0x000000, "Member 'WBP_Settings_C_GetNewPageIndex::PageOffset' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, NewPageIndex) == 0x000004, "Member 'WBP_Settings_C_GetNewPageIndex::NewPageIndex' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000008, "Member 'WBP_Settings_C_GetNewPageIndex::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, CallFunc_GetChildrenCount_ReturnValue) == 0x00000C, "Member 'WBP_Settings_C_GetNewPageIndex::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, CallFunc_Add_IntInt_ReturnValue) == 0x000010, "Member 'WBP_Settings_C_GetNewPageIndex::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, CallFunc_Subtract_IntInt_ReturnValue) == 0x000014, "Member 'WBP_Settings_C_GetNewPageIndex::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GetNewPageIndex, CallFunc_LoopAround_ReturnValue) == 0x000018, "Member 'WBP_Settings_C_GetNewPageIndex::CallFunc_LoopAround_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.GoToPage
// 0x0020 (0x0020 - 0x0000)
struct WBP_Settings_C_GoToPage final
{
public:
	int32                                         PageIndex;                                         // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWidget*                                CallFunc_GetActiveWidget_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetChildrenCount_ReturnValue;             // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Clamp_ReturnValue;                        // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_GoToPage) == 0x000008, "Wrong alignment on WBP_Settings_C_GoToPage");
static_assert(sizeof(WBP_Settings_C_GoToPage) == 0x000020, "Wrong size on WBP_Settings_C_GoToPage");
static_assert(offsetof(WBP_Settings_C_GoToPage, PageIndex) == 0x000000, "Member 'WBP_Settings_C_GoToPage::PageIndex' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GoToPage, CallFunc_GetActiveWidget_ReturnValue) == 0x000008, "Member 'WBP_Settings_C_GoToPage::CallFunc_GetActiveWidget_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GoToPage, CallFunc_GetChildrenCount_ReturnValue) == 0x000010, "Member 'WBP_Settings_C_GoToPage::CallFunc_GetChildrenCount_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GoToPage, CallFunc_Subtract_IntInt_ReturnValue) == 0x000014, "Member 'WBP_Settings_C_GoToPage::CallFunc_Subtract_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_GoToPage, CallFunc_Clamp_ReturnValue) == 0x000018, "Member 'WBP_Settings_C_GoToPage::CallFunc_Clamp_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnAddedToFocusPath
// 0x0008 (0x0008 - 0x0000)
struct WBP_Settings_C_OnAddedToFocusPath final
{
public:
	struct FFocusEvent                            InFocusEvent;                                      // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
};
static_assert(alignof(WBP_Settings_C_OnAddedToFocusPath) == 0x000004, "Wrong alignment on WBP_Settings_C_OnAddedToFocusPath");
static_assert(sizeof(WBP_Settings_C_OnAddedToFocusPath) == 0x000008, "Wrong size on WBP_Settings_C_OnAddedToFocusPath");
static_assert(offsetof(WBP_Settings_C_OnAddedToFocusPath, InFocusEvent) == 0x000000, "Member 'WBP_Settings_C_OnAddedToFocusPath::InFocusEvent' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnChildFocused
// 0x0010 (0x0010 - 0x0000)
struct WBP_Settings_C_OnChildFocused final
{
public:
	class UNativeWidgetHost*                      FocusedWidgetHost;                                 // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	struct FFocusEvent                            FocusEvent;                                        // 0x0008(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
static_assert(alignof(WBP_Settings_C_OnChildFocused) == 0x000008, "Wrong alignment on WBP_Settings_C_OnChildFocused");
static_assert(sizeof(WBP_Settings_C_OnChildFocused) == 0x000010, "Wrong size on WBP_Settings_C_OnChildFocused");
static_assert(offsetof(WBP_Settings_C_OnChildFocused, FocusedWidgetHost) == 0x000000, "Member 'WBP_Settings_C_OnChildFocused::FocusedWidgetHost' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnChildFocused, FocusEvent) == 0x000008, "Member 'WBP_Settings_C_OnChildFocused::FocusEvent' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnFocusReceived
// 0x01B0 (0x01B0 - 0x0000)
struct WBP_Settings_C_OnFocusReceived final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	struct FFocusEvent                            InFocusEvent;                                      // 0x0038(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
};
static_assert(alignof(WBP_Settings_C_OnFocusReceived) == 0x000008, "Wrong alignment on WBP_Settings_C_OnFocusReceived");
static_assert(sizeof(WBP_Settings_C_OnFocusReceived) == 0x0001B0, "Wrong size on WBP_Settings_C_OnFocusReceived");
static_assert(offsetof(WBP_Settings_C_OnFocusReceived, MyGeometry) == 0x000000, "Member 'WBP_Settings_C_OnFocusReceived::MyGeometry' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnFocusReceived, InFocusEvent) == 0x000038, "Member 'WBP_Settings_C_OnFocusReceived::InFocusEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnFocusReceived, ReturnValue) == 0x000040, "Member 'WBP_Settings_C_OnFocusReceived::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnFocusReceived, CallFunc_Handled_ReturnValue) == 0x0000F8, "Member 'WBP_Settings_C_OnFocusReceived::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnPressCancel
// 0x01B0 (0x01B0 - 0x0000)
struct WBP_Settings_C_OnPressCancel final
{
public:
	struct FKeyEvent                              KeyEvent;                                          // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
};
static_assert(alignof(WBP_Settings_C_OnPressCancel) == 0x000008, "Wrong alignment on WBP_Settings_C_OnPressCancel");
static_assert(sizeof(WBP_Settings_C_OnPressCancel) == 0x0001B0, "Wrong size on WBP_Settings_C_OnPressCancel");
static_assert(offsetof(WBP_Settings_C_OnPressCancel, KeyEvent) == 0x000000, "Member 'WBP_Settings_C_OnPressCancel::KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressCancel, ReturnValue) == 0x000040, "Member 'WBP_Settings_C_OnPressCancel::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressCancel, CallFunc_Handled_ReturnValue) == 0x0000F8, "Member 'WBP_Settings_C_OnPressCancel::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnPressedNewTab
// 0x0048 (0x0048 - 0x0000)
struct WBP_Settings_C_OnPressedNewTab final
{
public:
	struct FKeyEvent                              KeyEvent;                                          // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UWBP_GameMenu_Tab_C*                    PressedButtonTab;                                  // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_OnPressedNewTab) == 0x000008, "Wrong alignment on WBP_Settings_C_OnPressedNewTab");
static_assert(sizeof(WBP_Settings_C_OnPressedNewTab) == 0x000048, "Wrong size on WBP_Settings_C_OnPressedNewTab");
static_assert(offsetof(WBP_Settings_C_OnPressedNewTab, KeyEvent) == 0x000000, "Member 'WBP_Settings_C_OnPressedNewTab::KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressedNewTab, PressedButtonTab) == 0x000040, "Member 'WBP_Settings_C_OnPressedNewTab::PressedButtonTab' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnPressedTab
// 0x0048 (0x0048 - 0x0000)
struct WBP_Settings_C_OnPressedTab final
{
public:
	struct FKeyEvent                              KeyEvent;                                          // 0x0000(0x0040)(BlueprintVisible, BlueprintReadOnly, Parm)
	class UWBP_Button_Tab_C*                      PressedButtonTab;                                  // 0x0040(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_OnPressedTab) == 0x000008, "Wrong alignment on WBP_Settings_C_OnPressedTab");
static_assert(sizeof(WBP_Settings_C_OnPressedTab) == 0x000048, "Wrong size on WBP_Settings_C_OnPressedTab");
static_assert(offsetof(WBP_Settings_C_OnPressedTab, KeyEvent) == 0x000000, "Member 'WBP_Settings_C_OnPressedTab::KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressedTab, PressedButtonTab) == 0x000040, "Member 'WBP_Settings_C_OnPressedTab::PressedButtonTab' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnPressNext
// 0x01B8 (0x01B8 - 0x0000)
struct WBP_Settings_C_OnPressNext final
{
public:
	struct FKeyEvent                              KeyEvent;                                          // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	int32                                         CallFunc_GetNewPageIndex_NewPageIndex;             // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_FC[0x4];                                       // 0x00FC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x0100(0x00B8)()
};
static_assert(alignof(WBP_Settings_C_OnPressNext) == 0x000008, "Wrong alignment on WBP_Settings_C_OnPressNext");
static_assert(sizeof(WBP_Settings_C_OnPressNext) == 0x0001B8, "Wrong size on WBP_Settings_C_OnPressNext");
static_assert(offsetof(WBP_Settings_C_OnPressNext, KeyEvent) == 0x000000, "Member 'WBP_Settings_C_OnPressNext::KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressNext, ReturnValue) == 0x000040, "Member 'WBP_Settings_C_OnPressNext::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressNext, CallFunc_GetNewPageIndex_NewPageIndex) == 0x0000F8, "Member 'WBP_Settings_C_OnPressNext::CallFunc_GetNewPageIndex_NewPageIndex' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressNext, CallFunc_Handled_ReturnValue) == 0x000100, "Member 'WBP_Settings_C_OnPressNext::CallFunc_Handled_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.OnPressPrevious
// 0x01B8 (0x01B8 - 0x0000)
struct WBP_Settings_C_OnPressPrevious final
{
public:
	struct FKeyEvent                              KeyEvent;                                          // 0x0000(0x0040)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	struct FEventReply                            ReturnValue;                                       // 0x0040(0x00B8)(Parm, OutParm, ReturnParm)
	struct FEventReply                            CallFunc_Handled_ReturnValue;                      // 0x00F8(0x00B8)()
	int32                                         CallFunc_GetNewPageIndex_NewPageIndex;             // 0x01B0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_OnPressPrevious) == 0x000008, "Wrong alignment on WBP_Settings_C_OnPressPrevious");
static_assert(sizeof(WBP_Settings_C_OnPressPrevious) == 0x0001B8, "Wrong size on WBP_Settings_C_OnPressPrevious");
static_assert(offsetof(WBP_Settings_C_OnPressPrevious, KeyEvent) == 0x000000, "Member 'WBP_Settings_C_OnPressPrevious::KeyEvent' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressPrevious, ReturnValue) == 0x000040, "Member 'WBP_Settings_C_OnPressPrevious::ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressPrevious, CallFunc_Handled_ReturnValue) == 0x0000F8, "Member 'WBP_Settings_C_OnPressPrevious::CallFunc_Handled_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_OnPressPrevious, CallFunc_GetNewPageIndex_NewPageIndex) == 0x0001B0, "Member 'WBP_Settings_C_OnPressPrevious::CallFunc_GetNewPageIndex_NewPageIndex' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.PreConstruct
// 0x0001 (0x0001 - 0x0000)
struct WBP_Settings_C_PreConstruct final
{
public:
	bool                                          IsDesignTime;                                      // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_PreConstruct) == 0x000001, "Wrong alignment on WBP_Settings_C_PreConstruct");
static_assert(sizeof(WBP_Settings_C_PreConstruct) == 0x000001, "Wrong size on WBP_Settings_C_PreConstruct");
static_assert(offsetof(WBP_Settings_C_PreConstruct, IsDesignTime) == 0x000000, "Member 'WBP_Settings_C_PreConstruct::IsDesignTime' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.RefreshTabSelection
// 0x0028 (0x0028 - 0x0000)
struct WBP_Settings_C_RefreshTabSelection final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_GameMenu_Tab_C*                    CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_GetActiveWidgetIndex_ReturnValue;         // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(WBP_Settings_C_RefreshTabSelection) == 0x000008, "Wrong alignment on WBP_Settings_C_RefreshTabSelection");
static_assert(sizeof(WBP_Settings_C_RefreshTabSelection) == 0x000028, "Wrong size on WBP_Settings_C_RefreshTabSelection");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_Settings_C_RefreshTabSelection::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, Temp_int_Loop_Counter_Variable) == 0x000004, "Member 'WBP_Settings_C_RefreshTabSelection::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_Add_IntInt_ReturnValue) == 0x000008, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_Array_Get_Item) == 0x000010, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_GetActiveWidgetIndex_ReturnValue) == 0x000018, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_GetActiveWidgetIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_Array_Length_ReturnValue) == 0x00001C, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x000020, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_RefreshTabSelection, CallFunc_Less_IntInt_ReturnValue) == 0x000021, "Member 'WBP_Settings_C_RefreshTabSelection::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function WBP_Settings.WBP_Settings_C.SetupTabs
// 0x0068 (0x0068 - 0x0000)
struct WBP_Settings_C_SetupTabs final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UWBP_GameMenu_Tab_C*                    CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPCBuild_ReturnValue;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsPCBuild_ReturnValue_1;                  // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23[0x1];                                       // 0x0023(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(const struct FKeyEvent& KeyEvent, class UWBP_GameMenu_Tab_C* PressedButtonTab)> K2Node_CreateDelegate_OutputDelegate; // 0x0024(0x0010)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_34[0x4];                                       // 0x0034(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class UWBP_GameMenu_Tab_C*>            K2Node_MakeArray_Array;                            // 0x0038(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWBP_GameMenu_Tab_C*>            K2Node_MakeArray_Array_1;                          // 0x0048(0x0010)(ReferenceParm, ContainsInstancedReference)
	TArray<class UWBP_GameMenu_Tab_C*>            K2Node_Select_Default;                             // 0x0058(0x0010)(ReferenceParm, ContainsInstancedReference)
};
static_assert(alignof(WBP_Settings_C_SetupTabs) == 0x000008, "Wrong alignment on WBP_Settings_C_SetupTabs");
static_assert(sizeof(WBP_Settings_C_SetupTabs) == 0x000068, "Wrong size on WBP_Settings_C_SetupTabs");
static_assert(offsetof(WBP_Settings_C_SetupTabs, Temp_int_Array_Index_Variable) == 0x000000, "Member 'WBP_Settings_C_SetupTabs::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_Array_Get_Item) == 0x000008, "Member 'WBP_Settings_C_SetupTabs::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'WBP_Settings_C_SetupTabs::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, Temp_int_Loop_Counter_Variable) == 0x000014, "Member 'WBP_Settings_C_SetupTabs::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, Temp_bool_Variable) == 0x000018, "Member 'WBP_Settings_C_SetupTabs::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_Less_IntInt_ReturnValue) == 0x000019, "Member 'WBP_Settings_C_SetupTabs::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_Add_IntInt_ReturnValue) == 0x00001C, "Member 'WBP_Settings_C_SetupTabs::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_IsPCBuild_ReturnValue) == 0x000020, "Member 'WBP_Settings_C_SetupTabs::CallFunc_IsPCBuild_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_Not_PreBool_ReturnValue) == 0x000021, "Member 'WBP_Settings_C_SetupTabs::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, CallFunc_IsPCBuild_ReturnValue_1) == 0x000022, "Member 'WBP_Settings_C_SetupTabs::CallFunc_IsPCBuild_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, K2Node_CreateDelegate_OutputDelegate) == 0x000024, "Member 'WBP_Settings_C_SetupTabs::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, K2Node_MakeArray_Array) == 0x000038, "Member 'WBP_Settings_C_SetupTabs::K2Node_MakeArray_Array' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, K2Node_MakeArray_Array_1) == 0x000048, "Member 'WBP_Settings_C_SetupTabs::K2Node_MakeArray_Array_1' has a wrong offset!");
static_assert(offsetof(WBP_Settings_C_SetupTabs, K2Node_Select_Default) == 0x000058, "Member 'WBP_Settings_C_SetupTabs::K2Node_Select_Default' has a wrong offset!");

}

