#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapCursor

#include "Basic.hpp"

#include "WBP_MapCursor_classes.hpp"
#include "WBP_MapCursor_parameters.hpp"


namespace SDK
{

// Function WBP_MapCursor.WBP_MapCursor_C.ExecuteUbergraph_WBP_MapCursor
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_MapCursor_C::ExecuteUbergraph_WBP_MapCursor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapCursor_C", "ExecuteUbergraph_WBP_MapCursor");

	Params::WBP_MapCursor_C_ExecuteUbergraph_WBP_MapCursor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_MapCursor.WBP_MapCursor_C.OnLeaveIcon
// (BlueprintCallable, BlueprintEvent)

void UWBP_MapCursor_C::OnLeaveIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapCursor_C", "OnLeaveIcon");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_MapCursor.WBP_MapCursor_C.OnReachedIcon
// (BlueprintCallable, BlueprintEvent)

void UWBP_MapCursor_C::OnReachedIcon()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_MapCursor_C", "OnReachedIcon");

	UObject::ProcessEvent(Func, nullptr);
}

}

