#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_EXPGauge

#include "Basic.hpp"

#include "WBP_EXPGauge_classes.hpp"
#include "WBP_EXPGauge_parameters.hpp"


namespace SDK
{

// Function WBP_EXPGauge.WBP_EXPGauge_C.ExecuteUbergraph_WBP_EXPGauge
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EXPGauge_C::ExecuteUbergraph_WBP_EXPGauge(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "ExecuteUbergraph_WBP_EXPGauge");

	Params::WBP_EXPGauge_C_ExecuteUbergraph_WBP_EXPGauge Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.Initialize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_EXPGauge_C::Initialize(class AActor* Actor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "Initialize");

	Params::WBP_EXPGauge_C_Initialize Parms{};

	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.OnExperienceValueChanged
// (BlueprintCallable, BlueprintEvent)

void UWBP_EXPGauge_C::OnExperienceValueChanged()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "OnExperienceValueChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.OnLevelUp
// (BlueprintCallable, BlueprintEvent)

void UWBP_EXPGauge_C::OnLevelUp()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "OnLevelUp");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.RefreshLevelText
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_EXPGauge_C::RefreshLevelText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "RefreshLevelText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.SequenceEvent
// (BlueprintCallable, BlueprintEvent)

void UWBP_EXPGauge_C::SequenceEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "SequenceEvent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.SequenceEvent__ENTRYPOINTWBP_EXPGauge
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_EXPGauge_C::SequenceEvent__ENTRYPOINTWBP_EXPGauge()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "SequenceEvent__ENTRYPOINTWBP_EXPGauge");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_EXPGauge.WBP_EXPGauge_C.SetRatio
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Value                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bPlayAnimation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_EXPGauge_C::SetRatio(double Value, bool bPlayAnimation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_EXPGauge_C", "SetRatio");

	Params::WBP_EXPGauge_C_SetRatio Parms{};

	Parms.Value = Value;
	Parms.bPlayAnimation = bPlayAnimation;

	UObject::ProcessEvent(Func, &Parms);
}

}

