#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Extra_EntryName

#include "Basic.hpp"

#include "WBP_Extra_EntryName_classes.hpp"
#include "WBP_Extra_EntryName_parameters.hpp"


namespace SDK
{

// Function WBP_Extra_EntryName.WBP_Extra_EntryName_C.BndEvt__WBP_Extra_EntryName_LeftArrow_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Extra_EntryName_C::BndEvt__WBP_Extra_EntryName_LeftArrow_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Extra_EntryName_C", "BndEvt__WBP_Extra_EntryName_LeftArrow_Button_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Extra_EntryName.WBP_Extra_EntryName_C.BndEvt__WBP_Extra_EntryName_RightArrow_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UWBP_Extra_EntryName_C::BndEvt__WBP_Extra_EntryName_RightArrow_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Extra_EntryName_C", "BndEvt__WBP_Extra_EntryName_RightArrow_Button_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Extra_EntryName.WBP_Extra_EntryName_C.ExecuteUbergraph_WBP_Extra_EntryName
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Extra_EntryName_C::ExecuteUbergraph_WBP_Extra_EntryName(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Extra_EntryName_C", "ExecuteUbergraph_WBP_Extra_EntryName");

	Params::WBP_Extra_EntryName_C_ExecuteUbergraph_WBP_Extra_EntryName Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Extra_EntryName.WBP_Extra_EntryName_C.SetCanChangeEntry
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bCanChangeEntry_0                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Extra_EntryName_C::SetCanChangeEntry(bool bCanChangeEntry_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Extra_EntryName_C", "SetCanChangeEntry");

	Params::WBP_Extra_EntryName_C_SetCanChangeEntry Parms{};

	Parms.bCanChangeEntry_0 = bCanChangeEntry_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Extra_EntryName.WBP_Extra_EntryName_C.SetEntryName
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class FText&                      EntryName_0                                            (BlueprintVisible, BlueprintReadOnly, Parm)

void UWBP_Extra_EntryName_C::SetEntryName(const class FText& EntryName_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Extra_EntryName_C", "SetEntryName");

	Params::WBP_Extra_EntryName_C_SetEntryName Parms{};

	Parms.EntryName_0 = std::move(EntryName_0);

	UObject::ProcessEvent(Func, &Parms);
}

}

