#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InventoryPage

#include "Basic.hpp"

#include "WBP_InventoryPage_classes.hpp"
#include "WBP_InventoryPage_parameters.hpp"


namespace SDK
{

// Function WBP_InventoryPage.WBP_InventoryPage_C.AddChildToContainer
// (Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Content                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::AddChildToContainer(class UWidget* Content)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "AddChildToContainer");

	Params::WBP_InventoryPage_C_AddChildToContainer Parms{};

	Parms.Content = Content;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.CanShowInventoryItem
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FDataTableRowHandle&       Handle                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// bool*                                   bCanShow                                               (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::CanShowInventoryItem(const struct FDataTableRowHandle& Handle, bool* bCanShow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "CanShowInventoryItem");

	Params::WBP_InventoryPage_C_CanShowInventoryItem Parms{};

	Parms.Handle = std::move(Handle);

	UObject::ProcessEvent(Func, &Parms);

	if (bCanShow != nullptr)
		*bCanShow = Parms.bCanShow;
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_InventoryPage_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.CreateList
// (Protected, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UInventoryComponent*              Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EInventoryItemType                      ItemType_0                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::CreateList(class UInventoryComponent* Target, EInventoryItemType ItemType_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "CreateList");

	Params::WBP_InventoryPage_C_CreateList Parms{};

	Parms.Target = Target;
	Parms.ItemType_0 = ItemType_0;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.ExecuteUbergraph_WBP_InventoryPage
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::ExecuteUbergraph_WBP_InventoryPage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "ExecuteUbergraph_WBP_InventoryPage");

	Params::WBP_InventoryPage_C_ExecuteUbergraph_WBP_InventoryPage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.FocusEntryInRowAtIndex
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    bFromTop                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   IndexInRow                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::FocusEntryInRowAtIndex(bool bFromTop, int32 IndexInRow)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "FocusEntryInRowAtIndex");

	Params::WBP_InventoryPage_C_FocusEntryInRowAtIndex Parms{};

	Parms.bFromTop = bFromTop;
	Parms.IndexInRow = IndexInRow;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.GetItemHolder
// (Protected, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UPanelWidget**                    ItemHolder                                             (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::GetItemHolder(class UPanelWidget** ItemHolder)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "GetItemHolder");

	Params::WBP_InventoryPage_C_GetItemHolder Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (ItemHolder != nullptr)
		*ItemHolder = Parms.ItemHolder;
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.OnFocusReceived
// (BlueprintCosmetic, Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FFocusEvent&               InFocusEvent                                           (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FEventReply                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FEventReply UWBP_InventoryPage_C::OnFocusReceived(const struct FGeometry& MyGeometry, const struct FFocusEvent& InFocusEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "OnFocusReceived");

	Params::WBP_InventoryPage_C_OnFocusReceived Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InFocusEvent = std::move(InFocusEvent);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_InventoryPage.WBP_InventoryPage_C.OnItemFocused
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWBP_InventoryEntry_C*            Entry                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void UWBP_InventoryPage_C::OnItemFocused(class UWBP_InventoryEntry_C* Entry)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_InventoryPage_C", "OnItemFocused");

	Params::WBP_InventoryPage_C_OnItemFocused Parms{};

	Parms.Entry = Entry;

	UObject::ProcessEvent(Func, &Parms);
}

}

